name: My First Actions
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  - push
jobs:
  intro:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "Bob Saget" > ./name.txt
      - run: echo "The NAME env variable is $(cat name.txt)"
      - uses: actions/upload-artifact@v4
        with:
          name: name.txt
          path: ./name.txt
  checkout:
    runs-on: ubuntu-latest
    needs: intro
    steps:
      - name: Checks out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
  list-files:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "The job's status is ${{ job.status }}"
  say-hello:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: name.txt
          path: ./name.txt
      - run: echo "Hello World!"
      - run: echo "The NAME env variable is $(cat name.txt)"